name: bookify 

services:
  bookify.api:
    image: ${DOCKER_REGISTRY-}bookifyapi
    container_name: Bookify.Api
    build:
      context: .
      dockerfile: Bookify.Api/Dockerfile
    depends_on:
        bookify-db:
            condition: service_healthy
    networks:
        - bookify-net

  bookify-db:
    image: postgres:13
    container_name: Bookify-Db
    environment:
        POSTGRES_DB: bookify
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    volumes:
        - bookify_pg_data:/var/lib/postgresql/data
    ports:
        - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d bookify"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
       - bookify-net

  bookify-idp:
    image: quay.io/keycloak/keycloak:latest
    container_name: Bookify.Identity
    command: start-dev 
    environment:
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
        KC_HOSTNAME: bookify-idp 
        KC_HTTP_ENABLED: true
        KC_HTTP_PORT: 8080  
        KC_HOSTNAME_STRICT: false
    volumes:
        - keycloak_data:/opt/keycloak/data
    ports:
        - "18080:8080"
        # - "18443:8443"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8080/health/ready"]
        interval: 10s
        timeout: 5s
        retries: 5
    depends_on:
      bookify-db:
        condition: service_healthy
    networks:
        - bookify-net

volumes:
  keycloak_data:
  bookify_pg_data:
  
networks:
  bookify-net:
    driver: bridge